# Generated by Django 4.2.19 on 2025-02-19 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='actual',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actual',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actual_images/'),
        ),
        migrations.AddField(
            model_name='actual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
