# Generated by Django 4.2.19 on 2025-02-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0002_rename_created_at_actual_date_actual_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actual',
            options={'verbose_name': 'Актуальная информация', 'verbose_name_plural': 'Актуальная информация'},
        ),
    ]
