# Generated by Django 4.2.19 on 2025-02-23 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0003_alter_actual_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='actual',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
