# Generated by Django 4.2.19 on 2025-02-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionsmodel',
            old_name='name',
            new_name='region_name',
        ),
    ]
