# Generated by Django 4.2.19 on 2025-02-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_rename_regionsmodel_regions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
