# Generated by Django 4.2.19 on 2025-02-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_controlpanel_delete_control_panel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlpanel',
            options={'verbose_name': 'Панель управления', 'verbose_name_plural': 'Панель управления'},
        ),
    ]
