# Generated by Django 4.2.19 on 2025-02-23 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_htmltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltemplate',
            name='template_name',
            field=models.CharField(default='base_template', max_length=200),
        ),
        migrations.AlterField(
            model_name='htmltemplate',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
