# Generated by Django 4.2.19 on 2025-02-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Региональные Новости', 'verbose_name_plural': 'Региональные Новости'},
        ),
    ]
