# Generated by Django 4.2.19 on 2025-02-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegrambot_delete_telegram_botmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Телеграм бот', 'verbose_name_plural': 'Телеграм боты'},
        ),
    ]
